'use client';
import { formatQuestionText } from '@/../data/question_presentation.mjs';
import { useState } from 'react';
import Link from 'next/link';
import { Pause,Play,RefreshCw,Download,Upload,ShieldCheck,ArrowLeft } from 'lucide-react';

const labels={english:'English',accountancy:'Accountancy',business_studies:'Business Studies',economics:'Economics'};
const dollars=value=>Number.isFinite(value)?`${value.toFixed(value>0 && value<.01?6:2)}`:'Awaiting receipts';
const money=value=>Number.isFinite(value)?`$${dollars(value)}`:'Awaiting receipts';
function download(name,value) {const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export default function QuestionFactoryDashboard({initial,preview=false}) {
  const [data,setData]=useState(initial),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const snapshot=data.control?.snapshot || {};
  const settled=snapshot.costs?.stages?.reduce((sum,stage)=>sum+stage.settled_usd,0);
  const held=snapshot.costs?.stages?.reduce((sum,stage)=>sum+stage.held_usd,0);
  const affordable=snapshot.achievable_published ?? (snapshot.batch?.budget_scenarios?.[0]?.additional_approved_affordable!=null?snapshot.batch.approved_unique+snapshot.batch.budget_scenarios[0].additional_approved_affordable:null);
  const shortfall=snapshot.shortfall_usd ?? (Number.isFinite(snapshot.batch?.conditional_lifetime_to_10000_usd)?Math.max(0,snapshot.batch.conditional_lifetime_to_10000_usd-50):null);
  async function act(action,payload) {
    setBusy(action);setError('');setNotice('');
    try {
      const response=await fetch('/api/admin/question-factory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})});
      const next=await response.json();if(!response.ok)throw new Error(next.error || 'The action could not finish.');
      if(action==='import_review'){setNotice(`${next.applied} screening receipts imported. No questions were certified.`);await refresh();}else setData(next);
    }catch(e){setError(e.message.replaceAll('_',' '));}finally{setBusy('');}
  }
  async function refresh() {
    const response=await fetch('/api/admin/question-factory',{cache:'no-store'}),next=await response.json();
    if(!response.ok)throw new Error(next.error || 'Could not refresh');setData(next);
  }
  async function exportReview() {
    setBusy('export');setError('');try{const response=await fetch('/api/admin/question-factory?export=legacy',{cache:'no-store'});const payload=await response.json();if(!response.ok)throw new Error(payload.error);download('mockmob-subscription-review.json',payload);setNotice(`${payload.bundles.length} review bundles exported; additional API cost $0.`);}catch(e){setError(e.message);}finally{setBusy('');}
  }
  async function importReview(event) {
    const file=event.target.files?.[0];event.target.value='';if(!file)return;
    if(file.size>1000000){setError('Choose a review payload smaller than 1 MB.');return;}
    try{await act('import_review',JSON.parse(await file.text()));}catch{setError('This file could not be read as JSON.');}
  }
  const disabled=preview || Boolean(busy);
  const button='inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-white/15 px-4 py-2 text-sm font-medium text-white hover:bg-white/10 disabled:opacity-40 disabled:cursor-not-allowed';
  return <main className="min-h-screen bg-[#0f130e] text-[#f4f5f0] px-4 py-6 sm:px-8"><div className="mx-auto max-w-6xl space-y-6">
    <Link href="/admin" className="inline-flex min-h-11 items-center gap-2 text-sm text-zinc-400"><ArrowLeft size={16}/>Admin</Link>
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-[#d2f000]">Content operations</p><h1 className="mt-2 text-3xl font-bold">Question factory</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-zinc-400">Usable coverage → focused source excerpts → Luna generation → independent validation → atomic publication → updated coverage.</p></div><span className="rounded-full border border-white/15 px-4 py-2 text-sm">{data.control?.paused===false?'Running':'Paused'} · {data.control?.phase || 'pilot'}</span></header><p className="text-xs leading-relaxed text-zinc-500">2026 baseline used provisionally for 2027: 50 questions, 60 minutes, +5 / −1 / 0, maximum raw score 250. Final 2027 rules are unconfirmed. All correctness gates must pass before craft scores 7–10 can approve an item.</p>
    {preview && <p className="rounded-xl border border-amber-400/30 bg-amber-400/10 p-4 text-sm">Local commissioning preview. Saved local worker receipts appear here; controls are disabled and publication requires the staging and production gates.</p>}
    {(!data.available || snapshot.blocker) && <div role="status" className="rounded-xl border border-amber-400/30 bg-amber-400/10 p-4"><strong className="text-sm">Publication gate</strong><p className="mt-1 break-words text-sm text-amber-100">{(data.blocker || snapshot.blocker || 'Waiting for source and calibration evidence').replaceAll('_',' ')}</p></div>}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
      ['New published',`${data.counts.total.toLocaleString('en-IN')} / 10,000`,'Unique newly published inventory'],
      ['Content spend',money(settled),`${money(held)} held for pending requests; $50 lifetime ceiling`],
      ['Forecast for 10,000',money(snapshot.forecast_usd),'Estimate from observed eligibility and token use'],
      ['Legacy review','$0 API','Consumes included subscription usage']
    ].map(([title,value,detail])=><section key={title} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><p className="text-xs text-zinc-400">{title}</p><p className="mt-3 break-words text-xl font-semibold">{value}</p><p className="mt-2 text-xs leading-relaxed text-zinc-500">{detail}</p></section>)}</div>
    {Number.isFinite(snapshot.pilot?.generated) && <p role="status" className="rounded-xl border border-white/10 p-4 text-sm">{snapshot.pilot.historical?'Previous commissioning':'Commissioning'}: {snapshot.pilot.generated} / {snapshot.pilot.target} generated · {snapshot.pilot.eligible} {snapshot.pilot.historical?'previously passed':'eligible'} · {snapshot.pilot.quarantined} quarantined. {snapshot.pilot.historical?'Earlier passes require revalidation under the current quality policy.':snapshot.batch?.newly_published>0?`${snapshot.batch.newly_published} approved questions published.`:'Eligible drafts await publication gates.'}</p>}
    {snapshot.reviewed_cohort && <section className="rounded-xl border border-white/15 p-4 text-sm"><h2 className="font-semibold">Latest reviewed cohort</h2><p className="mt-2">{snapshot.reviewed_cohort.reviewed_strong} strong drafts · {snapshot.reviewed_cohort.reviewed_ordinary} ordinary practice drafts · {snapshot.reviewed_cohort.display_restored} display restored · {snapshot.reviewed_cohort.needs_correction} need correction · {snapshot.reviewed_cohort.duplicate_surplus} duplicate ideas.</p><p className="mt-2 text-zinc-400">{snapshot.reviewed_cohort.potential_review_supported} potential usable drafts. Renewed academic verification is pending; none are published. Review scores do not establish perfect accuracy.</p></section>}
    {snapshot.quality_audit && <section className="rounded-xl border border-amber-400/30 p-4 text-sm"><h2 className="font-semibold">Independent audit of the previous 48 passes</h2><p className="mt-2">{snapshot.quality_audit.approve} have no blocking defect found · {snapshot.quality_audit.suspect} need corrections · {snapshot.quality_audit.incomplete} lacks evidence. This is not a perfection guarantee.</p><p className="mt-2 text-amber-100">Current calibration: {snapshot.quality_calibration.valid_eligible} / {snapshot.quality_calibration.valid_sample_size} previously labelled valid examples pass; {snapshot.quality_calibration.audit_challenges_accepted} audited problem drafts still pass checks. Generation is paused.</p></section>}
    {Number.isFinite(snapshot.cost_per_published_usd) && <p className="text-sm text-zinc-400">Measured cost per eligible question: ${snapshot.cost_per_published_usd.toFixed(4)}. Estimated inventory within budget: {affordable?.toLocaleString('en-IN') || '—'} questions; estimated shortfall ${dollars(shortfall)}. Forecasts use recorded pricing and the observed unique yield; they remain conditional.</p>}
    <section className="rounded-2xl border border-white/10 p-5"><h2 className="text-lg font-semibold">Recorded content cost by stage</h2><p className="mt-2 text-xs leading-relaxed text-zinc-400">Lifetime ledger, including calibration, rejected candidates and repairs. Settled token costs and pending reservations are shown separately.</p>{snapshot.costs?.stages?.length?<ul className="mt-4 space-y-3">{snapshot.costs.stages.map(item=><li key={`${item.provider}:${item.model}:${item.stage}`} className="break-words text-sm"><p>{item.stage.replaceAll('_',' ')} · {item.model}</p><p className="mt-1 text-xs text-zinc-400">${item.settled_usd.toFixed(4)} settled · ${item.held_usd.toFixed(4)} held · {item.settled_requests} completed / {item.open_requests} pending</p><p className="mt-1 text-xs text-zinc-500">{item.input_tokens.toLocaleString('en-IN')} input / {item.output_tokens.toLocaleString('en-IN')} output tokens, including {item.reasoning_tokens.toLocaleString('en-IN')} reasoning tokens{item.usage_missing_requests?` · ${item.usage_missing_requests} receipts without token detail`:''}</p></li>)}</ul>:<p className="mt-4 text-sm text-zinc-500">No paid generation receipts yet.</p>}</section>
    <section className="rounded-2xl border border-white/10 p-5"><h2 className="text-lg font-semibold">Controls</h2><div className="mt-4 flex flex-wrap gap-3">
      <button className={button} disabled={disabled || !data.available} onClick={()=>act(data.control?.paused===false?'pause':'resume')}>{data.control?.paused===false?<Pause size={16}/>:<Play size={16}/>} {data.control?.paused===false?'Pause':'Resume'}</button>
      <button className={button} disabled={disabled} onClick={async()=>{setBusy('refresh');try{await refresh();}catch(e){setError(e.message);}finally{setBusy('');}}}><RefreshCw size={16}/>Refresh</button>
      <button className={button} disabled={disabled} onClick={exportReview}><Download size={16}/>Export review bundles</button>
      <label className={`${button} ${disabled?'opacity-40 cursor-not-allowed':'cursor-pointer'}`}><Upload size={16}/>Import review result<input type="file" accept="application/json,.json" aria-label="Import subscription review result" disabled={disabled} onChange={importReview} className="sr-only"/></label>
      <button className={button} disabled={disabled || !data.available} onClick={()=>act('release_1000')}><ShieldCheck size={16}/>Check 1,000 gate</button>
      <button className={button} disabled={disabled || !data.available} onClick={()=>act('release_10000')}>Check 10,000 gate</button>
    </div><p className="mt-3 text-xs leading-relaxed text-zinc-500">Checkpoint controls evaluate source, calibration, pilot and cost receipts. Uncertain questions remain quarantined.</p>
    {error && <p role="alert" className="mt-4 break-words text-sm text-red-300">{error}</p>}{notice && <p role="status" className="mt-4 text-sm text-[#d2f000]">{notice}</p>}</section>
    <section><h2 className="text-lg font-semibold">Source readiness and coverage</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.sources.map(source=><article key={source.subject} className="rounded-2xl border border-white/10 p-5"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">{labels[source.subject]}</h3><span className={`text-xs ${source.ready?'text-[#d2f000]':'text-amber-300'}`}>{source.ready?'Source pack ready':source.authenticated_anchors?'Reference coverage required':'Sources required'}</span></div><p className="mt-3 text-2xl font-semibold">{data.counts.by_subject[source.subject] || 0}<span className="text-sm font-normal text-zinc-500"> / 2,500 published</span></p><p className="mt-2 text-xs text-zinc-400">{source.reference_documents ?? 0} reference documents and stimuli · {source.authenticated_anchors} optional authenticated style anchors</p><p className="mt-2 break-words text-xs leading-relaxed text-zinc-500">{source.ready?source.syllabus_version:source.reason==='reference_coverage_beyond_reserved_calibration_required'?'Needs supported references for generation; calibration examples stay reserved.':'Needs relevant authoritative excerpts and reuse evidence.'}</p>{data.scope_coverage?.find(s=>s.subject===source.subject) && <p className="mt-2 text-xs text-amber-100">Syllabus: {data.scope_coverage.find(s=>s.subject===source.subject).chapters.filter(c=>c.ready).length} / {data.scope_coverage.find(s=>s.subject===source.subject).chapters.length} chapters have reference excerpts; individual answer support is checked during validation.</p>}<details className="mt-3 text-xs text-zinc-400"><summary className="flex min-h-11 cursor-pointer items-center">Inspect chapter coverage</summary><ul className="space-y-2 pt-2">{(data.scope_coverage?.find(s=>s.subject===source.subject)?.chapters.map(c=>c.chapter) || source.chapters).map(chapter=><li key={chapter}>{chapter}: {(data.coverage || []).find(c=>c.subject===source.subject && c.chapter===chapter)?.published || 0} published · {(data.coverage || []).find(c=>c.subject===source.subject && c.chapter===chapter)?.usable ?? 0} usable{data.scope_coverage?.find(s=>s.subject===source.subject)?.chapters.find(c=>c.chapter===chapter)?.ready===false?' · source coverage required':''}</li>)}{source.missing_chapters?.map(chapter=><li key={chapter} className="text-amber-200">{chapter}: reference excerpts required</li>)}</ul></details></article>)}</div></section>
    <div className="grid gap-4 lg:grid-cols-2"><section className="min-w-0 rounded-2xl border border-white/10 p-5"><h2 className="text-lg font-semibold">Recent jobs and quarantine</h2>{data.jobs.length?<ul className="mt-3 divide-y divide-white/10">{data.jobs.map(job=><li key={job.id} className="py-3 text-sm"><p>{labels[job.subject]} · {job.chapter}</p><p className="mt-1 break-words text-xs text-zinc-400">{job.state} · {job.stage} {job.result?.reasons?.join(', ')}</p><details className="mt-2"><summary className="flex min-h-11 cursor-pointer items-center text-xs text-zinc-400">Inspect question and receipts</summary><p className="mt-2 whitespace-pre-line">{formatQuestionText(job.candidate?.body) || 'Candidate not recorded yet'}</p><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap break-words rounded-lg bg-black/30 p-3 text-xs">{JSON.stringify({options:job.candidate?.options,key:job.candidate?.correct_answer,explanation:job.candidate?.explanation,provenance:job.candidate?.provenance,checks:job.candidate?.evidence?.record?.checks || job.result?.checks,reasons:job.result?.reasons},null,2)}</pre></details></li>)}</ul>:<p className="mt-4 text-sm text-zinc-500">No jobs recorded. The pilot starts after source registration and budget reconciliation.</p>}</section><section className="rounded-2xl border border-white/10 p-5"><h2 className="text-lg font-semibold">Open answer disputes</h2>{data.disputes.length?<ul className="mt-3 divide-y divide-white/10">{data.disputes.map(d=><li key={d.id} className="py-3 text-sm"><p className="break-all">{d.question_id}</p><p className="mt-1 text-xs text-zinc-400">{d.reason} · withheld pending revalidation</p><p className="mt-1 break-all text-xs text-zinc-500">Content version {d.content_hash}</p></li>)}</ul>:<p className="mt-4 text-sm text-zinc-500">No open disputes returned.</p>}</section></div>
    {Object.keys(snapshot.rejection_reasons || {}).length>0 && <section className="rounded-2xl border border-white/10 p-5"><h2 className="text-lg font-semibold">Rejection reasons</h2><ul className="mt-3 space-y-2 text-xs text-zinc-400">{Object.entries(snapshot.rejection_reasons).map(([reason,count])=><li key={reason} className="break-words">{reason.replaceAll('_',' ')}: {count}</li>)}</ul></section>}
    <p className="text-xs leading-relaxed text-zinc-500">Subscription screening is separate from academic publication evidence. Model agreement does not prove truth. Student AI retains its separate $25 per IST month guard.</p>
  </div></main>;
}
