// Local, read-only release audit. No database connection or provider dispatch.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { CONCEPT_BLUEPRINTS, validatePathway } from '../../data/learning_engine.js';
import { RELEASE_GATES, CURRENT_OFFER, TARGET_OFFER } from '../../data/capabilities.js';
const read=name=>JSON.parse(readFileSync(new URL(`../../data/${name}`,import.meta.url),'utf8'));
const sources=read('source_registry.json'),calibration=read('calibration_manifest.json'),pathways=read('recovery_pathways.json');
const missing=CONCEPT_BLUEPRINTS.map(c=>({concept:c.id,subject:c.subject,missing:!pathways.pathways.some(p=>p.id===c.id),requirements:['permitted versioned source','authenticated pathway digest and rules','independent held-out calibration','six independent families','complete delayed sequence']}));
const invalid=[];for(const p of pathways.pathways){try{validatePathway(p);}catch(error){invalid.push({id:p.id,error:error.message});}}
const report={generatedAt:new Date().toISOString(),mode:'local_read_only',databaseApplied:false,paidCalls:0,sourceCount:Object.keys(sources.sources || {}).length,calibrationState:calibration.state,pathwayState:pathways.state,pathwayCount:pathways.pathways.length,missing,invalid,releaseGates:RELEASE_GATES,currentOffer:CURRENT_OFFER,targetOffer:TARGET_OFFER,flags:{sessionMigration:'off unless LEARNING_SESSIONS_ENABLED=true',recovery:'off unless durable sessions, released manifest, current signed question evidence and registered pathway digest all pass',persistentRateLimits:'off unless PERSISTENT_LIMITS_ENABLED=true',decisionCoaching:'not released',newOffer:'not released',optionalPaidAi:'paused; zero authorized runtime funding'},nextAcceptanceCriterion:'Stage 1: explicit staging migration and authenticated owner-bound baseline/session → review → shared-plan flow. Stage 2 remains blocked on sources and academic calibration.'};
mkdirSync(new URL('../../docs/brain/reports/',import.meta.url),{recursive:true});writeFileSync(new URL('../../docs/brain/reports/learning-preflight.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({sourceCount:report.sourceCount,calibrationState:report.calibrationState,pathwayCount:report.pathwayCount,currentPrice:CURRENT_OFFER.rupees,newPriceEnabled:false,report:'docs/brain/reports/learning-preflight.json'}));
