import {loadEnvFile} from 'node:process';
import {readFileSync,writeFileSync} from 'node:fs';
import {createClient} from '@supabase/supabase-js';
import {createServerClient} from '@supabase/ssr';
import {attachBankPassages,readAllRows} from '../lib/bankSnapshot.mjs';
import {currentRegistry,publicationEligibility} from '../../../data/evidence_registry.js';
if(!process.argv.includes('--approved-production'))throw Error('explicit_production_read_required');
loadEnvFile('.env.local');
const url=process.env.NEXT_PUBLIC_SUPABASE_URL;
if(url!=='https://isrxrxzjocewrdureyhp.supabase.co')throw Error('production_identity_mismatch');
const db=createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});
const publications=await readAllRows(db,'question_factory_publications','question_id','question_id');
const rows=[];
for(let i=0;i<publications.length;i+=100){const {data,error}=await db.from('questions').select('*').in('id',publications.slice(i,i+100).map(p=>p.question_id));if(error)throw error;rows.push(...data);}
const snapshot={registry:currentRegistry(),manifest:JSON.parse(readFileSync('data/calibration_manifest.json','utf8'))},reasons={};
const local=(await attachBankPassages(db,rows)).map(q=>publicationEligibility(q,snapshot));
for(const result of local)if(!result.eligible)for(const reason of result.reasons)reasons[reason]=(reasons[reason]||0)+1;
const {data:owner,error:ownerError}=await db.auth.admin.getUserById(process.env.CUET_CONTENT_AUTHOR_ID);
if(ownerError||!owner.user?.email)throw Error('existing_owner_required');
const link=await db.auth.admin.generateLink({type:'magiclink',email:owner.user.email});if(link.error)throw link.error;
let jar=[];const client=createServerClient(url,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,{cookies:{getAll:()=>jar,setAll:v=>jar=v}});
const otp=await client.auth.verifyOtp({token_hash:link.data.properties.hashed_token,type:link.data.properties.verification_type});if(otp.error)throw otp.error;
const started=Date.now(),response=await fetch('https://www.mockmob.in/api/admin/question-factory',{headers:{Cookie:jar.map(c=>c.name+'='+c.value).join('; ')},signal:AbortSignal.timeout(90000)});
if(response.status!==200)throw Error('authenticated_admin_http_'+response.status);
const overview=await response.json();
if(!overview.verification_diagnostics)throw Error('diagnostic_release_required');
const proof={at:new Date().toISOString(),scope:'Actual production stored evidence checked with local signing configuration, compared with protected deployed evidence diagnostics. This does not prove student retrieval.',local:{rows:rows.length,eligible:local.filter(r=>r.eligible).length,rejection_reasons:reasons},deployed:{available:overview.available,counts:overview.counts,diagnostics:overview.verification_diagnostics,duration_ms:Date.now()-started},paid_provider_calls:0,emails_sent:0,production_writes:0};
writeFileSync('artifacts/question-factory/execution-2026-10-07/production/evidence-configuration-diagnosis.json',JSON.stringify(proof,null,2)+'\n');
console.log(JSON.stringify(proof));
