import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {BudgetLedger} from '../lib/budgetLedger.mjs';
import {freezeCompactBenchmark} from '../lib/compactBenchmark.mjs';
import {FACTORY_VERIFIER_VERSION,sourceMaterial} from '../lib/factoryEvidence.mjs';
import {hashJSON} from '../../../data/question_factory_policy.mjs';
const dir='artifacts/question-factory/execution-2026-10-07',read=p=>JSON.parse(readFileSync(p)),save=(p,v)=>writeFileSync(p,JSON.stringify(v,null,2)+'\n');
if(FACTORY_VERIFIER_VERSION!=='luna-gemini-cuET-v6.2')throw Error('v62_contract_required');
const ledger=new BudgetLedger('data/pipeline-budget.sqlite'),registry=read('data/source_registry.json'),items=[];
const ref=(id,locator)=>({id,version:registry.sources[id].version,locator,support_hash:registry.sources[id].supports[locator]});
function passage(id,text){const file=dir+'/'+id+'.txt';writeFileSync(file,text);registry.sources[id]={...registry.sources['mockmob-original-stimulus-narrative-passage'],id,title:'Original fictional held-out stimulus',facts:{stimulus:{text}},supports:{stimulus:hashJSON(text)},file,extraction_file:file,identity_sha256:createHash('sha256').update(text).digest('hex'),url:'local://mockmob/heldout/'+id};registry.sources[id].extraction_sha256=registry.sources[id].identity_sha256;registry.packs['original-english-reference-v1'].document_ids.push(id);return ref(id,'stimulus');}
function add(subject,chapter,body,options,key,explanation,refs,{route='conceptual',type='conceptual_mcq',difficulty='medium',stimulus=''}={}){
 const id=hashJSON({benchmark:'frozen-v62',item:items.length+1}).slice(0,32),family_id='heldout:'+id,spec=registry.exam_specs[subject];sourceMaterial(registry,refs);
 const candidate={id,subject,chapter,body,options,correct_answer:key,explanation,route,difficulty,question_type:type,passage_text:stimulus,family_id,source_refs:refs,provenance:{kind:'original_practice',anchor_id:null,adaptation_family:family_id,adaptation_type:null,syllabus_version:spec.syllabus_version,pattern_version:spec.pattern_version,source_pack_id:`original-${subject}-reference-v1`,source_pack_version:1}};
 registry.families[family_id]={state:'active',version:1,kind:'heldout_source_oracle'};items.push({id,expected_valid:true,category:'valid_'+difficulty,candidate,oracle:{key,source_refs:refs,basis:explanation,independently_established_before_validation:true},state:'queued'});
}
try{
 add('english','Match the Following','Match the words with their meanings.\nList-I: (A) Diligent (B) Hostile (C) Obsolete\nList-II: (I) Unfriendly (II) No longer used (III) Showing care and effort\nChoose the correct matching.',['(A)-(I), (B)-(III), (C)-(II)','(A)-(III), (B)-(II), (C)-(I)','(A)-(III), (B)-(I), (C)-(II)','(A)-(II), (B)-(I), (C)-(III)'],'C','Diligent describes careful effort; hostile means unfriendly; obsolete means no longer used. Thus A-III, B-I, C-II is correct.',[ref('oxford-quality-diligent','definition'),ref('oxford-quality-hostile','definition'),ref('oxford-quality-obsolete','definition')],{type:'matching',difficulty:'easy'});
 const text='In a fictional school, Mira volunteered to record birds visiting the courtyard. She initially wrote down only their colours. Her teacher suggested noting the time and behaviour as well. After a week, Mira compared her notes and saw that the same brown bird arrived just before lunch on four days. She decided to keep observing before calling it a regular visitor, because the week had been unusually quiet.';
 add('english','Narrative Passage','What does Mira’s decision at the end suggest about her approach?',['She prefers more observations before reaching a firm conclusion.','She believes colours alone identify every bird.','She has decided that no birds visit regularly.','She considers the time of a visit unimportant.'],'A','Mira decides to keep observing before labelling the bird a regular visitor. This supports caution about drawing a firm conclusion from one unusual week; it does not establish that birds never visit regularly.',[passage('mockmob-v62-birds',text)],{route:'passage',type:'reading_comprehension',stimulus:text});
 const text2='In a fictional museum, a guide found that visitors often missed a small map beside the entrance. She first moved the map to a board at eye level. A week later, she watched visitors and noticed that some still asked for directions. She then added coloured arrows leading from the board to the main galleries. On the next busy morning, fewer visitors asked where the galleries were.';
 add('english','Narrative Passage','Arrange these events as reported: (P) Coloured arrows were added. (Q) The guide moved the map. (R) Fewer visitors asked for gallery directions. (S) The guide observed that some visitors still asked for directions.',['Q-P-S-R','S-Q-P-R','P-Q-S-R','Q-S-P-R'],'D','The map was moved first, then visitor behaviour was observed, then arrows were added, and finally fewer requests for directions were reported: Q-S-P-R.',[passage('mockmob-v62-museum',text2)],{route:'passage',type:'sequence_ordering',stimulus:text2,difficulty:'easy'});
 const inventory=ref('ncert-leac205','pdf-page-20'),cash=ref('ncert-leac206','span-a507d1e4b724');
 add('accountancy','Accounting Ratios','Opening inventory is ₹1,20,000 and closing inventory is ₹1,80,000. The inventory turnover ratio is 8 times. Revenue from operations is ₹15,00,000. Using the arithmetic average of opening and closing inventory, what is gross profit?',['₹12,00,000','₹3,00,000','₹1,50,000','₹13,20,000'],'B','Average inventory = (₹1,20,000 + ₹1,80,000)/2 = ₹1,50,000. Cost of revenue = 8 × ₹1,50,000 = ₹12,00,000. Gross profit = revenue minus cost of revenue = ₹15,00,000 − ₹12,00,000 = ₹3,00,000. The other choices confuse cost, average inventory, or closing inventory with the required gross profit.',[inventory],{route:'numerical',type:'numerical_calculation',difficulty:'hard'});
 add('accountancy','Cash Flow Statement','During the year a company receives ₹6,00,000 from a new long-term bank loan and repays ₹2,40,000 of principal on an older bank loan. These are its only financing cash flows, and neither amount includes interest. What is the net cash flow from financing activities?',['₹8,40,000 inflow','₹2,40,000 outflow','₹3,60,000 inflow','₹6,00,000 inflow'],'C','A new bank loan is a financing inflow and repayment of borrowed principal is a financing outflow. Net financing flow = ₹6,00,000 − ₹2,40,000 = ₹3,60,000 inflow. Adding both amounts ignores their opposite directions; using either amount alone omits a stated flow.',[cash],{route:'numerical',type:'numerical_calculation'});
 add('accountancy','Cash Flow Statement','A company issues equity shares for cash and also repays the principal of a bank loan. Which classification correctly describes these two cash flows, respectively?',['Financing inflow; financing outflow','Financing outflow; financing inflow','Investing inflow; operating outflow','Operating inflow; investing outflow'],'A','Cash received from issuing shares is a financing inflow. Cash repayment of borrowed principal is a financing outflow. Both change capital or borrowings; the other pairs misclassify their direction or activity.',[cash],{type:'case_application',difficulty:'easy'});
 add('economics','Production & Costs','With capital and all other inputs fixed, total product is zero with no workers. The marginal products of the first, second and third workers are 8, 11 and 9 units, respectively. What is total product with three workers?',['9 units','11 units','19 units','28 units'],'D','The source states that total product is the sum of marginal products up to that input level. Starting from zero, total product = 8 + 11 + 9 = 28 units. Nine is only the third worker’s marginal product; 19 omits the third worker.',[ref('ncert-leec203','p5-c0')],{route:'numerical',type:'numerical_calculation'});
 add('economics','Income Determination','In a closed two-sector economy without government, ex ante aggregate demand for final goods is ₹620 crore and planned consumption expenditure is ₹470 crore. What is planned investment expenditure?',['₹1,090 crore','₹150 crore','₹470 crore','₹620 crore'],'B','In the stated two-sector model, AD = C + I. Therefore I = AD − C = ₹620 crore − ₹470 crore = ₹150 crore. Adding the figures or repeating either given amount does not solve for investment.',[ref('ncert-leec104','quality-v3-pdf-page-4-5fac2a1794')],{route:'numerical',type:'numerical_calculation',difficulty:'easy'});
 add('economics','Production & Costs','Which statement correctly relates total product to the marginal products of successive units of a variable input?',['Total product equals only the last unit’s marginal product.','Total product is the arithmetic mean of marginal products.','Total product is the sum of marginal products up to that input level.','Total product equals the largest marginal product.'],'C','The supplied NCERT excerpt states that total product is the sum of marginal products of successive units up to the input level considered. It is not the last, mean, or largest marginal product.',[ref('ncert-leec203','p5-c0')],{difficulty:'easy'});
 const delegation=ref('ncert-lebs105','quality-v4-910ff72d0f84');
 add('business_studies','Organising','A supervisor makes an employee responsible for completing a task but gives the employee no authority to make the decisions needed for it. Which requirement of effective delegation is directly violated?',['Informal communication must follow a planned route.','The employee must form a separate product division.','All authority must remain with top management.','Authority granted should be commensurate with assigned responsibility.'],'D','The source expressly requires authority to be commensurate with assigned responsibility. Assigning the task while withholding the decision authority needed for it violates that requirement. The other statements do not state the relevant principle.',[delegation],{type:'case_application'});
 add('business_studies','Organising','Consider the statements: (I) In a formal organisation, authority flows from superior to subordinate. (II) Responsibility for an assigned duty flows upwards to the superior. Which are correct?',['I only','II only','Both I and II','Neither I nor II'],'C','The NCERT excerpt states that authority flows top to bottom and responsibility flows upward from subordinate to superior. Both statements are correct.',[delegation],{type:'statement_selection',difficulty:'easy'});
 add('business_studies','Organising','Employees from different departments voluntarily form a lunch group, and their friendships create an unofficial communication network. How is this network best classified?',['Formal organisation deliberately designed by management','Informal organisation arising from employee interaction','Functional structure created by grouping similar jobs','Divisional structure created around product lines'],'B','The supplied informal-organisation excerpt explains that employee interaction and social relationships create informal organisation. The described voluntary friendships fit that origin, whereas formal or departmental structures depend on deliberate organisational design.',[ref('ncert-lebs105','quality-v4-c8d4ce1fa39d'),ref('ncert-lebs105','quality-v4-e5d85ed5309a'),ref('ncert-lebs105','quality-v4-18f392ccae68')],{type:'case_application'});
 const defect=(index,category,change,basis)=>{const original=items[index],id=hashJSON({benchmark:'frozen-v62',item:items.length+1}).slice(0,32),candidate=structuredClone(original.candidate);candidate.id=id;candidate.family_id='heldout:'+id;candidate.provenance.adaptation_family=candidate.family_id;change(candidate);registry.families[candidate.family_id]={state:'active',version:1,kind:'heldout_source_oracle'};items.push({id,expected_valid:false,category,candidate,oracle:{...original.oracle,basis},state:'queued'});};
 defect(3,'wrong_key',q=>q.correct_answer='A','The independently calculated gross profit is ₹3,00,000, option B.');
 defect(7,'wrong_key',q=>q.correct_answer='A','Investment = 620 − 470 = 150, option B.');
 defect(4,'multiple_correct',q=>q.options=['₹3,60,000 inflow','Positive net financing cash flow','₹2,40,000 outflow','₹8,40,000 outflow'],'Both first and second options are true.');
 defect(8,'multiple_correct',q=>q.options=['Sum of marginal products','Total of marginal products','Last marginal product','Mean marginal product'],'First two options are equivalent.');
 defect(3,'missing_assumptions',q=>q.body='Opening inventory is ₹1,20,000 and closing inventory is ₹1,80,000. Revenue from operations is ₹15,00,000. What is gross profit?','Without turnover or cost of revenue, gross profit cannot be determined.');
 defect(4,'missing_assumptions',q=>q.body='A company receives ₹6,00,000 from a new long-term bank loan and makes a payment on an older loan. What is net financing cash flow?','The repayment amount and whether it includes interest are missing.');
 defect(1,'unsupported_explanation',q=>q.explanation='Mira waited because a national law requires exactly sixty days of bird observation before recording a visitor.','The alleged national law is invented and unsupported.');
 defect(10,'unsupported_explanation',q=>q.explanation='Both are correct because responsibility can always be completely delegated and accountability flows downwards.','The explanation contradicts the supplied delegation principles.');
 defect(0,'out_of_syllabus',q=>{q.body='What is the chemical symbol of sodium?';q.options=['Na','S','N','So'];q.correct_answer='A';q.explanation='Sodium is Na.';},'Chemistry is outside English entitlement and dictionary support.');
 defect(9,'out_of_syllabus',q=>{q.body='Which part of a plant absorbs water from soil?';q.options=['Flower','Root','Fruit','Leaf'];q.correct_answer='B';q.explanation='The root absorbs water from soil.';},'Botany is outside Business Studies entitlement and supplied sources.');
 defect(6,'numerical_fault',q=>{q.options=['9 units','11 units','19 units','29 units'];q.correct_answer='D';q.explanation='8 + 11 + 9 = 29 units.';},'8 + 11 + 9 = 28, absent from the options.');
 defect(3,'numerical_fault',q=>{q.correct_answer='D';q.explanation='Cost of revenue is 8 times closing inventory, or ₹14,40,000, so gross profit is ₹13,20,000.';},'Using closing rather than average inventory is invalid and subtraction is also wrong.');
 const campaign=read(dir+'/campaign.json');
 if(campaign.jobs.some(j=>ledger.db.prepare('SELECT request_json FROM provider_batches UNION ALL SELECT request_json FROM provider_requests').all().some(r=>r.request_json.includes(j.id))))throw Error('bulk_already_started');
 registry.version++;const registration=freezeCompactBenchmark(items,{registry,ledger});campaign.verifier=FACTORY_VERIFIER_VERSION;campaign.registry_version=registry.version;
 campaign.validation_preflight_amendment={at:new Date().toISOString(),reason:'Preserve failed v6.1 denominator and receipts; distinguish tested academic knowledge from missing case assumptions and permit explicitly requested synonym phrases. No correctness gate relaxed. Freeze new items before bulk dispatch.'};
 save(dir+'/benchmark.json',{registration,fixtures:items});save(dir+'/campaign.json',campaign);save(dir+'/registry.json',registry);save('data/source_registry.json',registry);
 // Prior audit defects remain regression examples, revalidated under the new contract.
 ledger.db.prepare("UPDATE factory_candidates SET value=json_set(value,'$.state','queued') WHERE id LIKE 'v6-regression-%'").run();
 console.log(JSON.stringify({frozen_items:items.length,positives:12,controlled_defects:12,bulk_candidates:100,verifier:FACTORY_VERIFIER_VERSION,paid_requests:0}));
}finally{ledger.close();}
