import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {BudgetLedger} from '../lib/budgetLedger.mjs';
import {freezeCompactBenchmark} from '../lib/compactBenchmark.mjs';
import {FACTORY_VERIFIER_VERSION,sourceMaterial} from '../lib/factoryEvidence.mjs';
import {hashJSON} from '../../../data/question_factory_policy.mjs';
import {retrieveFocusedSources} from '../lib/focusedSources.mjs';
const dir='artifacts/question-factory/execution-2026-10-07',read=p=>JSON.parse(readFileSync(p)),save=(p,v)=>writeFileSync(p,JSON.stringify(v,null,2)+'\n');
const previous=read(dir+'/benchmark-results.json');
if(!previous.complete&&!existsSync('.cache/factory-v60/scripts/pipeline/tools/focusedFactory.mjs'))throw Error('preserved_completion_runner_required');
if(FACTORY_VERIFIER_VERSION!=='luna-gemini-cuET-v6.1')throw Error('v61_contract_required');
const ledger=new BudgetLedger('data/pipeline-budget.sqlite'),registry=read('data/source_registry.json'),items=[];
const ref=(id,locator)=>{const s=registry.sources[id];if(!s?.facts[locator])throw Error('exact_source_locator_missing:'+id+':'+locator);return {id,version:s.version,locator,support_hash:s.supports[locator]};};
function stimulus(id,text){const file=dir+'/'+id+'.txt';writeFileSync(file,text);const basis=registry.sources['mockmob-original-stimulus-narrative-passage'];
 registry.sources[id]={...basis,id,title:'Separate original held-out fictional reading stimulus',facts:{stimulus:{text}},supports:{stimulus:hashJSON(text)},file,extraction_file:file,identity_sha256:createHash('sha256').update(text).digest('hex'),url:'local://mockmob/heldout/'+id};registry.sources[id].extraction_sha256=registry.sources[id].identity_sha256;
 registry.packs['original-english-reference-v1'].document_ids.push(id);return ref(id,'stimulus');
}
function positive(subject,chapter,body,options,key,explanation,refs,{route='conceptual',type='conceptual_mcq',difficulty='medium',passage=''}={}){
 const id=hashJSON({benchmark:'frozen-v61',item:items.length+1}).slice(0,32),family_id='heldout:'+id,spec=registry.exam_specs[subject];
 sourceMaterial(registry,refs);
 const candidate={id,subject,chapter,body,options,correct_answer:key,explanation,route,difficulty,question_type:type,passage_text:passage,family_id,source_refs:refs,
  provenance:{kind:'original_practice',anchor_id:null,adaptation_family:family_id,adaptation_type:null,syllabus_version:spec.syllabus_version,pattern_version:spec.pattern_version,source_pack_id:`original-${subject}-reference-v1`,source_pack_version:1}};
 registry.families[family_id]={state:'active',version:1,kind:'heldout_source_oracle'};
 items.push({id,expected_valid:true,category:'valid_'+difficulty,candidate,oracle:{key,source_refs:refs,basis:explanation,independently_established_before_validation:true},state:'queued'});
}
try{
 positive('english','Vocabulary','In the sentence "The hillside had sparse vegetation", which phrase is closest in meaning to "sparse"?',['Densely crowded','Present in small amounts','Growing rapidly','Uniformly arranged'],'B','Sparse means present in small amounts or numbers, often spread over a large area. The sentence concerns how little vegetation is present, rather than its growth rate or arrangement.',[ref('oxford-quality-sparse','definition')],{type:'synonym',difficulty:'easy'});
 positive('english','Match the Following','Match List-I with List-II.\nList-I: (A) Frugal (B) Resolute (C) Candid\nList-II: (I) Determined (II) Open and honest (III) Economical in using resources\nChoose the correct matching.',['(A)-(III), (B)-(I), (C)-(II)','(A)-(I), (B)-(III), (C)-(II)','(A)-(II), (B)-(I), (C)-(III)','(A)-(III), (B)-(II), (C)-(I)'],'A','Frugal describes using only necessary resources; resolute means determined; candid means open and honest. Thus A-III, B-I and C-II is the only complete matching.',[ref('oxford-quality-frugal','definition'),ref('oxford-quality-resolute','definition'),ref('oxford-quality-candid','definition')],{type:'matching'});
 const story='In a fictional village workshop, Nila noticed that a lamp flickered whenever its cable moved. She switched off the power and asked the technician to inspect it. After replacing the damaged cable, the technician tested the lamp. Nila then carried the working lamp to the community hall. She told the organiser that noticing the fault had delayed the delivery but prevented them from using a damaged cable.';
 const storyRef=stimulus('mockmob-v61-workshop-stimulus',story);
 positive('english','Narrative Passage','Arrange these events in the order reported in the passage: (P) The technician tested the repaired lamp. (Q) Nila noticed the flickering. (R) Nila took the lamp to the hall. (S) The technician replaced the cable.',['Q-P-S-R','S-Q-P-R','Q-S-P-R','Q-S-R-P'],'C','The passage first reports noticing the flicker, then replacement of the damaged cable, then testing, and finally delivery to the hall: Q-S-P-R.',[storyRef],{route:'passage',type:'sequence_ordering',passage:story});
 const story2='In a fictional bookshop, Kabir chose a travel diary because he liked its cover. Before paying, he opened it and found that most pages contained blank tables for recording expenses. He put it back and chose a collection of travellers’ stories instead. On the way home, he told his sister that the first book would have been useful for planning a trip, but he wanted something to read that evening.';
 const storyRef2=stimulus('mockmob-v61-bookshop-stimulus',story2);
 positive('english','Narrative Passage','Why did Kabir change his choice of book?',['He wanted reading material rather than a diary for recording a trip.','The shopkeeper refused to sell the diary.','He disliked the diary’s cover.','He had stopped being interested in travel.'],'A','Kabir wanted something to read that evening, whereas the first book mainly offered blank expense tables. He still chose travellers’ stories, so the passage does not show that he lost interest in travel.',[storyRef2],{route:'passage',type:'reading_comprehension',passage:story2,difficulty:'easy'});
 const inventory=ref('ncert-leac205','pdf-page-20');
 positive('accountancy','Accounting Ratios','Revenue from operations is ₹18,00,000 and gross profit is 25% of revenue from operations. The inventory turnover ratio is 6 times and opening inventory is ₹1,80,000. Using the arithmetic average of opening and closing inventory, what is closing inventory?',['₹2,25,000','₹4,20,000','₹2,70,000','₹1,80,000'],'C','Gross profit is 25% × ₹18,00,000 = ₹4,50,000, so cost of revenue from operations is ₹13,50,000. Average inventory is ₹13,50,000/6 = ₹2,25,000. Closing inventory is 2 × ₹2,25,000 − ₹1,80,000 = ₹2,70,000. ₹2,25,000 confuses average with closing inventory; ₹4,20,000 uses revenue instead of cost; ₹1,80,000 assumes no inventory change.',[inventory],{route:'numerical',type:'numerical_calculation',difficulty:'hard'});
 positive('accountancy','Accounting Ratios','Consider these statements about inventory turnover: (I) Average inventory is the arithmetic average of opening and closing inventory. (II) Inventory turnover uses cost of revenue from operations in the numerator. (III) A high inventory turnover always establishes efficient buying, regardless of selling margin. Which statements are correct?',['I only','I and II only','II and III only','I and III only'],'B','I and II follow the stated formula. III is too broad: the source says high turnover needs careful interpretation because it can result from small-lot buying or quick sales at low margins.',[inventory],{type:'statement_selection'});
 positive('accountancy','Cash Flow Statement','A company repays ₹3,60,000 of the principal of a long-term bank loan by bank transfer. Interest is not included in this amount. How is the repayment classified in its cash flow statement?',['Operating cash outflow','Investing cash outflow','Financing cash inflow','Financing cash outflow'],'D','Repaying borrowed principal reduces borrowings and is a financing cash outflow. The stated amount excludes interest, so no classification convention for interest is needed.',[ref('ncert-leac206','span-a507d1e4b724')],{type:'case_application',difficulty:'easy'});
 positive('economics','Production & Costs','In the short run, a firm’s total cost rises from ₹80 at five units of output to ₹92 at six units. What is the marginal cost of the sixth unit?',['₹12','₹15.33','₹80','₹92'],'A','Marginal cost is change in total cost divided by change in output: (₹92 − ₹80)/(6 − 5) = ₹12. The ₹15.33 figure is the average cost at six units.',[ref('ncert-leec203','p9-c1856')],{route:'numerical',type:'numerical_calculation',difficulty:'easy'});
 positive('economics','Production & Costs','With capital and all other inputs fixed, total product is 20 units with three workers and 27 units with four workers. What is the marginal product of the fourth worker?',['27 units','6.75 units','7 units','20 units'],'C','Marginal product is the change in total product when one more worker is employed, with other inputs fixed: 27 − 20 = 7 units. The 6.75 figure is average product at four workers.',[ref('ncert-leec203','p5-c0')],{route:'numerical',type:'numerical_calculation'});
 positive('economics','Income Determination','In a closed two-sector economy without government, planned consumption expenditure is ₹350 crore and planned investment expenditure is ₹80 crore. What is ex ante aggregate demand for final goods?',['₹270 crore','₹80 crore','₹350 crore','₹430 crore'],'D','For the stated two-sector economy, ex ante aggregate demand is planned consumption plus planned investment: ₹350 crore + ₹80 crore = ₹430 crore.',[ref('ncert-leec104','quality-v3-pdf-page-4-5fac2a1794')],{route:'numerical',type:'numerical_calculation'});
 positive('business_studies','Organising','Match List-I with List-II.\nList-I: (A) Authority (B) Responsibility (C) Accountability\nList-II: (I) Answerability for an assigned task’s outcome (II) Right to command (III) Obligation to perform an assigned duty\nChoose the correct matching.',['(A)-(I), (B)-(III), (C)-(II)','(A)-(II), (B)-(III), (C)-(I)','(A)-(III), (B)-(II), (C)-(I)','(A)-(II), (B)-(I), (C)-(III)'],'B','Authority is the right to command, responsibility is the obligation to perform an assigned duty, and accountability is answerability for its outcome. The matching is A-II, B-III, C-I.',[ref('ncert-lebs105','quality-v4-910ff72d0f84')],{type:'matching'});
 positive('business_studies','Organising','A manufacturer groups all production jobs in one department, finance jobs in another and personnel jobs in a third. Which organising concept does this arrangement directly illustrate?',['Divisional structure based on products','Delegation of authority','Functional structure','Decentralisation of decisions'],'C','A functional structure groups similar or related jobs by function. The grouping criterion here is production, finance and personnel functions, not products. The described grouping does not itself establish how authority is delegated or how widely decisions are decentralised.',[ref('ncert-lebs105','quality-v4-18f392ccae68'),ref('ncert-lebs105','quality-v4-910ff72d0f84')],{type:'case_application',difficulty:'easy'});
 positive('business_studies','Organising','Consider these statements: (I) Formal organisation is deliberately designed by management. (II) Informal organisation arises from social interaction among employees. (III) Informal communication must always follow the formal scalar chain. Which statements are correct?',['I only','II and III only','I and III only','I and II only'],'D','I and II correctly identify the origins of formal and informal organisation. III is incorrect because informal communication does not follow a planned route and can move in any direction.',[ref('ncert-lebs105','quality-v4-e5d85ed5309a'),ref('ncert-lebs105','quality-v4-c8d4ce1fa39d')],{type:'statement_selection'});
 const defect=(index,category,change,basis)=>{const original=items[index],id=hashJSON({benchmark:'frozen-v61',item:items.length+1}).slice(0,32),candidate=structuredClone(original.candidate);candidate.id=id;candidate.family_id='heldout:'+id;candidate.provenance.adaptation_family=candidate.family_id;change(candidate);registry.families[candidate.family_id]={state:'active',version:1,kind:'heldout_source_oracle'};items.push({id,expected_valid:false,category,candidate,oracle:{...original.oracle,basis},state:'queued'});};
 defect(4,'wrong_key',q=>q.correct_answer='A','Independent calculation gives closing inventory ₹2,70,000, option C, not average inventory in A.');
 defect(9,'wrong_key',q=>q.correct_answer='A','350 + 80 = 430, option D, not A.');
 defect(7,'multiple_correct',q=>q.options=['₹12','More than ₹10','₹80','₹92'],'₹12 and more than ₹10 both describe the computed marginal cost.');
 defect(0,'multiple_correct',q=>q.options=['Present in small amounts','Thinly distributed','Crowded together','Abundant'],'The first two choices both express sparse vegetation.');
 defect(4,'missing_assumptions',q=>q.body='Revenue from operations is ₹15,00,000 and opening inventory is ₹1,50,000. What is the inventory turnover ratio?','Gross profit or cost of revenue and closing or average inventory are absent.');
 defect(8,'missing_assumptions',q=>q.body='A firm employs four workers. What is the marginal product of the fourth worker?','Total products for three and four workers are missing.');
 defect(3,'unsupported_explanation',q=>q.explanation='Kabir changed his choice because Indian law prohibits using travel diaries for leisure reading.','The alleged legal restriction has no basis in the fictional passage.');
 defect(5,'unsupported_explanation',q=>q.explanation='I and II are correct because every company is legally required to value inventory at its selling price.','The alleged legal valuation requirement is absent and does not support the formula.');
 defect(0,'out_of_syllabus',q=>{q.body='Which subatomic particle has a negative electric charge?';q.options=['Proton','Neutron','Electron','Photon'];q.correct_answer='C';q.explanation='An electron has a negative electric charge.';},'Particle physics is outside this English language entitlement and dictionary support.');
 defect(12,'out_of_syllabus',q=>{q.body='Which organ filters blood to produce urine?';q.options=['Heart','Kidney','Lung','Stomach'];q.correct_answer='B';q.explanation='The kidney filters blood to produce urine.';},'Human renal physiology is outside Business Studies and the supplied organising excerpts.');
 defect(7,'numerical_fault',q=>{q.options=['₹13','₹15.33','₹80','₹92'];q.correct_answer='A';q.explanation='92 minus 80 is 13, so marginal cost is ₹13.';},'92 − 80 = 12, absent from the choices; the calculation and key are faulty.');
 defect(4,'numerical_fault',q=>{q.correct_answer='B';q.explanation='Average inventory is revenue divided by turnover, 18,00,000/6 = 3,00,000. Closing inventory is 2 × 3,00,000 − 1,80,000 = 4,20,000.';},'The turnover numerator is cost of revenue, 13,50,000, giving average inventory 2,25,000 and closing inventory 2,70,000.');
 save(dir+'/benchmark-v60.json',read(dir+'/benchmark.json'));save(dir+'/benchmark-v60-results.json',previous);
 const campaign=read(dir+'/campaign.json');if(campaign.jobs.some(j=>ledger.db.prepare('SELECT request_json FROM provider_batches UNION ALL SELECT request_json FROM provider_requests').all().some(r=>r.request_json.includes(j.id))))throw Error('bulk_already_started_no_amendment');
 registry.version++;const registration=freezeCompactBenchmark(items,{registry,ledger});
 campaign.verifier=FACTORY_VERIFIER_VERSION;campaign.registry_version=registry.version;campaign.source_preflight_amendment={at:new Date().toISOString(),reason:'Independent checker rejected topic-only and exercise excerpts; normative heading spans replace them before any bulk dispatch. All original 100 IDs, topics, formats and denominator remain fixed.'};
 for(const job of campaign.jobs){job.research=retrieveFocusedSources(registry,job,ledger);job.source_refs=job.research.refs;
  if(job.subject==='english'&&job.chapter==='Vocabulary')job.topic+='; lexical target: '+job.source_refs[0].id.replace('oxford-quality-','');
 }
 for(const subject of ['english','accountancy','business_studies','economics'])campaign.jobs.filter(j=>j.subject===subject).sort((a,b)=>hashJSON({position_seed:a.id}).localeCompare(hashJSON({position_seed:b.id}))).forEach((j,i)=>j.requested_answer_position='ABCD'[i%4]);
 campaign.source_preflight_amendment.answer_positions='Balanced positions were seeded and permuted before any bulk dispatch to remove cyclic correlation with format.';
 save(dir+'/benchmark.json',{registration,fixtures:items});save(dir+'/campaign.json',campaign);save(dir+'/registry.json',registry);save('data/source_registry.json',registry);
 console.log(JSON.stringify({new_frozen_items:items.length,bulk_candidates:campaign.jobs.length,verifier:FACTORY_VERIFIER_VERSION,paid_requests:0}));
}finally{ledger.close();}
