import {readFileSync,writeFileSync,existsSync} from 'node:fs';
const root='artifacts/question-factory/continuation-500/',read=p=>JSON.parse(readFileSync(root+p));
const r=read('aggregate-report.json'),inspection=read('batch-inspection.json'),coverage=read('coverage-current.json');
const items=read('all-candidates.json'),reasons={};
for(const j of items.filter(j=>j.state==='quarantined'))for(const reason of j.result?.reasons||['reason_not_recorded'])reasons[reason]=(reasons[reason]||0)+1;
const money=v=>v==null?'not measured':'$'+v.toFixed(6),percent=(n,d)=>d?(100*n/d).toFixed(1)+'%':'not measured';
const table=(headers,rows)=>[headers.join(' | '),headers.map(()=> '---').join(' | '),...rows.map(row=>row.join(' | '))].map(line=>'| '+line+' |').join('\n');
const proof=environment=>{const p=root+environment+'-retrieval.json';return existsSync(p)?JSON.parse(readFileSync(p)):null;};
const stage=proof('staging'),prod=proof('production'),productionProofs=[];
const practice=existsSync(root+'practice-launch-checks.json')?read('practice-launch-checks.json'):null;
for(const c of r.cohorts){const p=c.directory+'/production/publication.json';if(existsSync(p))productionProofs.push(JSON.parse(readFileSync(p)));}
const stored=productionProofs.reduce((n,p)=>n+p.approved_unique,0),historical=r.economics.all_completed,current=r.economics;
const drivers=new Map();
const completedIds=new Set(items.filter(j=>j.cohort_complete).map(j=>j.id));
for(const receipt of read('receipts.json')){
 const d=receipt.receipt||{};if(!completedIds.has(d.candidate_id))continue;
 const key=[d.provider,receipt.model,d.stage,d.execution_mode||'unknown'].join(' / '),old=drivers.get(key)||{calls:0,cost:0,reasoning:0};
 old.calls++;old.cost+=(receipt.state==='settled'?receipt.actual:receipt.reserved)/1e6;
 old.reasoning+=d.usage?.output_tokens_details?.reasoning_tokens||d.usage?.thoughtsTokenCount||d.usage?.reasoning_tokens||0;drivers.set(key,old);
}
const lines=[
 '# MockMob generator execution and continuation evidence',
 '',`Snapshot: ${r.at}. This report preserves all ${r.registered_denominator} registered candidates, including failures. ${r.completed_denominator} candidates belong to completed cohorts; ${r.pending_candidates} candidates still need work.`,
 '',`**${r.unique_published_staging} unique usable questions are published in separate staging; the 500-question target is ${r.target_reached?'reached in staging':'not yet reached'}.** Saved atomic production publication receipts account for ${stored} questions. Production storage does not establish student availability.`,
 '',`Latest signed-in staging retrieval: ${stage?.at||'missing'}, ${stage?.unique_retrieved??0}/${stage?.expected_published??0}, passed=${stage?.passed??false}. Latest production student retrieval: ${prod?.at||'missing'}, ${prod?.unique_retrieved??0}/${prod?.expected_published??0}, passed=${prod?.passed??false}. These are dated evidence, not an assertion that later publications were already checked.`,
 '',practice?`Actual disposable-staging practice launches/submissions: ${practice.updated_at}, passed=${practice.passed}, ${practice.checks.filter(c=>c.state==='passed').length}/${practice.checks.length} checks. English quick practice and all four 50-question, 60-minute full mocks use actual new approved questions; launch replay creates no extra charge and submission replay is idempotent. Synthetic unanswered submissions score zero and are not observed learner outcomes. Prior failed checks are retained. The full-paper submission exceeded the payload limit before the bounded compressed encrypted-ticket fix; complete snapshots and existing valid p1 tickets remain intact. The disposable staging fixture added ${practice.test_credit_fixture?.added||0} non-monetary credits, separately recorded; production balances, entitlements, payment receipts and provider budgets are unchanged.`:'Actual practice launch evidence is not yet available.',
 '',table(['Cohort','Fixed denominator','Complete','Approved','Rejected','Pending','Gross cost','Held'],r.cohorts.map(c=>[c.id,c.denominator,c.complete,c.approved_unique,c.rejected??'pending',c.pending,money(c.cost.gross_usd),money(c.cost.held_usd)])),
 '', '## Costs and conditional forecast',
 '',`Lifetime receipt-settled usage: ${money(r.lifetime_settled_usd)}. Conservative open reservations: ${money(r.lifetime_conservative_holds_usd)}. Committed total: ${money(r.lifetime.committed_micro/1e6)} against the authorized $50 ceiling. Provider invoices obtained: ${r.provider_invoices_obtained}. Lifetime fully settled: ${r.fully_settled}. The historical OpenAI 503 hold is retained; an uncertain call is never assumed free.`,
 '',`All completed cohorts, including earlier authoring contracts: ${historical.unique_approved} unique approvals from ${r.completed_denominator} candidates (${percent(historical.unique_approved,r.completed_denominator)}), gross ${money(historical.gross_usd)}, gross per approved ${money(historical.gross_cost_per_approved_usd)}. Conditional marginal 10,000 cost: ${money(historical.conditional_marginal_10000_usd)}. Conditional lifetime cost to 10,000: ${money(historical.conditional_lifetime_to_10000_usd)}.`,
 '',`Current author contract only: ${current.comparable_unique_approved} approvals from ${current.comparable_denominator} completed candidates, gross ${money(current.comparable_gross_usd)}, per approved ${money(current.gross_cost_per_approved_usd)}, conditional lifetime 10,000 cost ${money(current.conditional_lifetime_to_10000_usd)}. All completed current-contract cohorts contribute; partial approvals and favorable-cohort selection do not.`,
 '', 'These forecasts include failed calls, rejected candidates, repairs, reasoning and validation. Existing lifetime commitments are added once, then the measured unit cost applies to the remaining target. Future source coverage, novelty, pricing and yield can change the result. A forecast below $100 is not authority to spend above $50. $60 and $70 remain scenarios. Neither usage receipts nor reservations are provider invoices.',
 '', historical.conditional_lifetime_to_10000_usd>70?'At the measured gross rate, even this mixed 7–9 practice bank does not fit 10,000 approved questions within $50–70. The measurement does not establish the cost of a uniformly premium bank; stronger craft and broader source coverage may cost more.':'The measured forecast must still be interpreted with its observed craft distribution and future source-coverage/yield uncertainty.',
 '',table(['Completed-candidate provider / model / stage / mode','Calls','Reasoning token subset','Gross usage'],[...drivers].sort((a,b)=>b[1].cost-a[1].cost).map(([key,d])=>[key,d.calls,d.reasoning,money(d.cost)])),
 '',`These driver rows include only receipts explicitly bound to completed candidate IDs; unattributed residual versus cohort gross is ${money(historical.gross_usd-[...drivers.values()].reduce((n,d)=>n+d.cost,0))}. Shared preparation/calibration is already retained in lifetime commitments, not double-counted in these rows.`,
 '',table(['Lifetime ceiling','Authority','Conditional total affordable at historical unit cost'],[50,60,70].map(cap=>[money(cap),cap===50?'authorized':'scenario only',historical.gross_cost_per_approved_usd?r.unique_published_staging+Math.floor(Math.max(0,cap-r.lifetime.committed_micro/1e6)/historical.gross_cost_per_approved_usd):'not measured'])),
 '', '## Quality, coverage and reliability',
 '',`Overall craft score distribution, using the lower independent judgment: ${JSON.stringify(inspection.overall_craft_scores)}. Missing scores: ${inspection.missing_scores}. Questions with an individual craft subscore below 7: ${inspection.questions_with_any_craft_subscore_below_7}. Overall scores 7–10 are permitted only after all mandatory gates pass; individual subscores remain honest diagnostics. This subset is not uniformly premium and ratings do not prove accuracy.`,
 '',`Approved subject counts: ${JSON.stringify(r.subjects)}. Formats: ${JSON.stringify(inspection.formats)}. Difficulty estimates: ${JSON.stringify(inspection.difficulty)}. Answer positions: ${JSON.stringify(inspection.answer_positions)}; longest same-position run ${inspection.longest_same_answer_run}. Aggregate deterministic duplicate findings: ${inspection.decisions.length}; flagged pairs: ${inspection.duplicate_pairs.length}. The exported inspection also includes position patterns by format. These checks do not guarantee exhaustive semantic novelty.`,
 '',`Coverage contains ${coverage.total_usable} usable questions across ${coverage.cells.length} official chapter cells (${coverage.cells.filter(c=>c.usable>0).length} with inventory). Fine-topic assignments use ${coverage.topic_contract}; ambiguous independent tags stay unclassified. Accountancy alternatives remain separate, with these cohorts using common plus financial analysis. The computerized alternative remains a tracked gap.`,
 '', 'The pipeline is coverage → focused cached source excerpts → GPT-6 Luna authoring → blinded Luna and independent Gemini checking → separate explanation verification → atomic approved publication → refreshed usable coverage. Original questions do not require PYQ anchors. Authentic PYQ labels retain authentication requirements. Exact source support, decisive assumptions and independently solved keys are mandatory; keyword overlap and downloaded documents are not evidence of an answer.',
 '', 'There are 19 criteria: 16 mandatory correctness/support/format/provenance gates and three scored craft dimensions. Wrong or uncertain keys, overlapping correct options, missing decisive assumptions, unsupported facts/explanations, syllabus mismatch, broken numericals and incomplete passages are rejected. One targeted repair is permitted, followed by revalidation; unresolved failures are quarantined. Reuse binds content, sources and verification contracts. No routine human review is required.',
 '', 'The frozen fresh benchmark has 24 items: 12 independently established valid answers and 12 controlled defects, including two each of wrong keys, overlapping answers, missing assumptions, unsupported explanations, syllabus mismatch and numerical faults. All 12 valid items survived and all 12 defects were rejected. This is a small dated measurement: its zero-observed false accepts still have a one-sided 95% upper bound of 22.09%. Previously inspected examples remain separate regression evidence. Live model misses and the subsequent conservative local withholding guards remain disclosed in the original cohort report; model agreement is not truth.',
 '', 'The verified 2026 baseline remains provisional for 2027: 50 questions, 60 minutes, +5 correct, −1 incorrect, zero unanswered, maximum raw score 250. English passages are capped at 300 words. Final 2027 rules are not confirmed.',
 '', '## Exports and reproduction',
 '', '`all-candidates.json` and `.csv` retain all registered candidates, keys, options, explanations, exact supporting excerpts, validation results, rejection reasons and item costs. `approved-published.json`, `rejected.json`, `receipts.json`, `batch-inspection.json`, `coverage-current.json` and `aggregate-report.json` provide the subset and accounting. Each fixed cohort also retains its own all-100 export, provider IDs, input preflight, benchmark contract and atomic publication receipts.',
 '', '```powershell',
 'npm.cmd run factory:staging-app',
 'node --use-system-ca scripts/pipeline/tools/continueCoverageCohorts.mjs --staging --approved-production --realtime-checks',
 'node --use-system-ca scripts/pipeline/tools/exportContinuation.mjs --staging',
 'node scripts/pipeline/tools/writeContinuationReport.mjs',
 'node --use-system-ca scripts/pipeline/tools/checkContinuationRetrieval.mjs --staging --minimum 500',
 'node --use-system-ca scripts/pipeline/tools/checkStagingPracticeLaunch.mjs --staging',
 'node --use-system-ca scripts/pipeline/tools/checkContinuationRetrieval.mjs --approved-production --base https://www.mockmob.in --minimum 500',
 'npm.cmd run test:factory', 'npm.cmd run test:recovery', '```',
 '', 'Resume the existing controller only after confirming its process has ended. Its persistent exclusive lease and budget guard retain accepted IDs, receipts and reservations across restart. Preserve the dirty checkout, SQLite ledger and runtime files, private source caches and campaign artifacts. Credentials remain in ignored local files and the owner-controlled deployment configuration.',
 '', '## Remaining work in this snapshot',
 '',`${r.pending_candidates} pending candidates still require their accepted provider work and validation to finish. The completed target also requires current production source-family registry deployment, owner entry of the existing CUET_EVIDENCE_SIGNING_KEY in the prepared Vercel Production secret form, and actual retrieval of at least 500 new approved items. Never substitute queued work, legacy inventory or fixtures for this target.`,
 '', 'The original report retains staging migration dry runs, authenticated admin controls, worker restart/idempotency, passage-group atomicity, rejected-item exclusion and dispute invalidation evidence. Only the saved additive factory migration was authorized on production. Existing payment/credit RPCs and the $25/IST-month student AI cap remain preserved. Passing local payment tests does not claim a captured live transaction.',
 '', 'Rejection reason counts (a candidate can have multiple reasons): '+JSON.stringify(reasons),
 ''];
writeFileSync(root+'REPORT.md',lines.join('\n'));console.log(JSON.stringify({report:root+'REPORT.md',snapshot:r.at,staging:r.unique_published_staging,production_receipts:stored,pending:r.pending_candidates}));
